#pragma once
#include "WcpOglUtility.h"
#include "VariableTable.h"
#include "Texture.h"
#include "TreFile.h"
#include <gl/glu.h>
#include <vector>

enum BOX_SIDE
{
	BOX_SIDE_0,
	BOX_SIDE_90,
	BOX_SIDE_180,
	BOX_SIDE_270,
	BOX_SIDE_BOTTOM,
	BOX_SIDE_TOP,
	BOX_SIDE_NONE,
};

class Skybox
{
public:
	Skybox(void);
	~Skybox(void);

	void Draw();
	void InitFromVariableTable(const VariableTable& table, const TreFile* treFile);
	bool InitHardcoded(const TreFile* treFile);

	void InitAutoGenerated(int numStars, const std::vector<Colour>& colours, int minSize, int maxSize, int textureSize = 1024);

private:
	bool LoadTexture(BOX_SIDE side, const char *filename, const TreFile* treFile);

	void GenerateStarFields(int numStars, const std::vector<Colour>& colours, int minSize, int maxSize, int textureSize, std::vector<unsigned char> outFaces[BOX_SIDE_NONE]) const;
	void UploadGenerated(BOX_SIDE side, const std::vector<unsigned char>& rgbaPixels, int textureSize);

	Texture		m_textures[BOX_SIDE_NONE];
};
