#include "Skybox.h"
#include <cmath>
#include <cstdlib>
#include <algorithm>

namespace
{
	struct FaceProjection
	{
		int   majorAxis;
		float majorSign;
		int   uAxis;
		float uSign;
		int   vAxis;
		float vSign;
	};

	const FaceProjection kFaceProjections[BOX_SIDE_NONE] =
	{
		/* BOX_SIDE_0      */ { 2, -1.0f, 0,  1.0f, 1,  1.0f },
		/* BOX_SIDE_90     */ { 0, -1.0f, 2, -1.0f, 1,  1.0f },
		/* BOX_SIDE_180    */ { 2,  1.0f, 0,  1.0f, 1, -1.0f },
		/* BOX_SIDE_270    */ { 0,  1.0f, 2, -1.0f, 1, -1.0f },
		/* BOX_SIDE_BOTTOM */ { 1, -1.0f, 0,  1.0f, 2, -1.0f },
		/* BOX_SIDE_TOP    */ { 1,  1.0f, 0, -1.0f, 2, -1.0f },
	};
}

Skybox::Skybox(void)
{
}

Skybox::~Skybox(void)
{
}

void Skybox::InitFromVariableTable(const VariableTable& table, const TreFile* treFile)
{
	string name;
	table.GetString("tex0", &name);
	LoadTexture(BOX_SIDE_0, name.c_str(), treFile);
	table.GetString("tex90", &name);
	LoadTexture(BOX_SIDE_90, name.c_str(), treFile);
	table.GetString("tex180", &name);
	LoadTexture(BOX_SIDE_180, name.c_str(), treFile);
	table.GetString("tex270", &name);
	LoadTexture(BOX_SIDE_270, name.c_str(), treFile);
	table.GetString("texBottom", &name);
	LoadTexture(BOX_SIDE_BOTTOM, name.c_str(), treFile);
	table.GetString("texTop", &name);
	LoadTexture(BOX_SIDE_TOP, name.c_str(), treFile);
}


bool Skybox::InitHardcoded(const TreFile* treFile)
{
	bool bReturn = true;
	if (LoadTexture(BOX_SIDE_0, "nebulas\\stars\\starbox_px.tga", treFile))
	{
		bReturn = LoadTexture(BOX_SIDE_90, "nebulas\\stars\\starbox_px.tga", treFile);
		bReturn &= LoadTexture(BOX_SIDE_180, "nebulas\\stars\\starbox_nx.tga", treFile);
		bReturn &= LoadTexture(BOX_SIDE_270, "nebulas\\stars\\starbox_nx.tga", treFile);
		bReturn &= LoadTexture(BOX_SIDE_BOTTOM, "nebulas\\stars\\starbox_ny.tga", treFile);
		bReturn &= LoadTexture(BOX_SIDE_TOP, "nebulas\\stars\\starbox_py.tga", treFile);
	}
	else
	{
		bReturn &= LoadTexture(BOX_SIDE_0, "nebulas\\stars\\sides.tga", treFile);
		bReturn &= LoadTexture(BOX_SIDE_90, "nebulas\\stars\\sides.tga", treFile);
		bReturn &= LoadTexture(BOX_SIDE_180, "nebulas\\stars\\sides.tga", treFile);
		bReturn &= LoadTexture(BOX_SIDE_270, "nebulas\\stars\\sides.tga", treFile);
		bReturn &= LoadTexture(BOX_SIDE_BOTTOM, "nebulas\\stars\\bottom.tga", treFile);
		bReturn &= LoadTexture(BOX_SIDE_TOP, "nebulas\\stars\\top.tga", treFile);
	}
	return bReturn;
}

bool Skybox::LoadTexture(BOX_SIDE side, const char *filename, const TreFile* treFile)
{
	FILE* file = NULL;
	DWORD fileSize;
	if (!treFile->GetFile(filename, &file, fileSize))
	{
		return false;
	}

	// FIXME: Use texture mgr
	m_textures[side].LoadFromTga(file, (size_t)fileSize, false);
	m_textures[side].SetClamp();

	return true;
}

void Skybox::InitAutoGenerated(int numStars, const std::vector<Colour>& colours, int minSize, int maxSize, int textureSize)
{
	if (colours.empty() || numStars <= 0 || textureSize <= 0)
		return;

	if (minSize > maxSize)
		std::swap(minSize, maxSize);

	std::vector<unsigned char> faces[BOX_SIDE_NONE];
	GenerateStarFields(numStars, colours, minSize, maxSize, textureSize, faces);

	for (int side = 0; side < BOX_SIDE_NONE; ++side)
		UploadGenerated((BOX_SIDE)side, faces[side], textureSize);
}

void Skybox::GenerateStarFields(int numStars, const std::vector<Colour>& colours, int minSize, int maxSize, int textureSize, std::vector<unsigned char> outFaces[BOX_SIDE_NONE]) const
{
	const int channels = 4;

	for (int side = 0; side < BOX_SIDE_NONE; ++side)
	{
		outFaces[side].assign(textureSize * textureSize * channels, 0);
		for (size_t i = 3; i < outFaces[side].size(); i += channels)
			outFaces[side][i] = 255;
	}

	int sizeRange = (std::max)(1, maxSize - minSize);
	const float kEpsilon = 0.05f;
	const float kTwoPi = wcpogl::pi * 2.f;

	for (int s = 0; s < numStars; ++s)
	{
		float z = 2.0f * (rand() / (float)RAND_MAX) - 1.0f;
		float phi = kTwoPi * (rand() / (float)RAND_MAX);
		float rxy = sqrtf((std::max)(0.0f, 1.0f - z * z));
		float dir[3] = { rxy * cosf(phi), rxy * sinf(phi), z };

		float radius = (float)(minSize + (rand() % sizeRange));
		radius = (std::max)(radius, 0.5f);

		const Colour& colour = colours[rand() % colours.size()];
		const float* rgba = colour.rgba();
		float r = rgba[0];
		float g = rgba[1];
		float b = rgba[2];

		float sigma = radius * 0.5f;
		float twoSigmaSq = 2.0f * sigma * sigma;
		float padded = radius * 3.0f;

		for (int side = 0; side < BOX_SIDE_NONE; ++side)
		{
			const FaceProjection& face = kFaceProjections[side];

			float ma = dir[face.majorAxis];
			if (ma * face.majorSign <= kEpsilon)
				continue;

			float pu = face.uSign * dir[face.uAxis] / ma;
			float pv = face.vSign * dir[face.vAxis] / ma;

			float cx = (0.5f + 0.5f * pu) * textureSize;
			float cy = (0.5f + 0.5f * pv) * textureSize;

			int minX = (std::max)(0, (int)(cx - padded));
			int maxX = (std::min)(textureSize - 1, (int)(cx + padded));
			int minY = (std::max)(0, (int)(cy - padded));
			int maxY = (std::min)(textureSize - 1, (int)(cy + padded));

			if (minX > maxX || minY > maxY)
				continue;

			std::vector<unsigned char>& pixels = outFaces[side];

			for (int y = minY; y <= maxY; ++y)
			{
				for (int x = minX; x <= maxX; ++x)
				{
					float dx = (x + 0.5f) - cx;
					float dy = (y + 0.5f) - cy;
					float distSq = dx * dx + dy * dy;

					float intensity = expf(-distSq / twoSigmaSq);
					if (intensity < 0.01f)
						continue;

					int idx = (y * textureSize + x) * channels;

					pixels[idx + 0] = (unsigned char)(std::min)(255.0f, pixels[idx + 0] + r * 255.0f * intensity);
					pixels[idx + 1] = (unsigned char)(std::min)(255.0f, pixels[idx + 1] + g * 255.0f * intensity);
					pixels[idx + 2] = (unsigned char)(std::min)(255.0f, pixels[idx + 2] + b * 255.0f * intensity);
				}
			}
		}
	}
}

void Skybox::UploadGenerated(BOX_SIDE side, const std::vector<unsigned char>& rgbaPixels, int textureSize)
{
	unsigned char* pixels = const_cast<unsigned char*>(rgbaPixels.data());
	m_textures[side].LoadFromMemory(pixels, textureSize, textureSize, 4, false);
	m_textures[side].SetClamp();
}


void Skybox::Draw()
{
	//glDisable(GL_CULL_FACE);
	//front face
	m_textures[BOX_SIDE_0].Bind(0);
	glBegin( GL_TRIANGLE_FAN );
	glTexCoord2f( 1.0f, 0.0f ); glVertex3d(-25.0, 25.0, -25.0);
	glTexCoord2f( 1.0f, 1.0f ); glVertex3d(-25.0, -25.0, -25.0);
	glTexCoord2f( 0.0f, 1.0f ); glVertex3d(25.0, -25.0, -25.0);
	glTexCoord2f( 0.0f, 0.0f ); glVertex3d(25.0, 25.0, -25.0);
	glEnd( );

	//back face
	m_textures[BOX_SIDE_180].Bind(0);
	glBegin( GL_TRIANGLE_FAN );
	glTexCoord2f( 1.0f, 0.0f ); glVertex3d(25.0, 25.0, 25.0);
	glTexCoord2f( 1.0f, 1.0f ); glVertex3d(25.0, -25.0, 25.0);
	glTexCoord2f( 0.0f, 1.0f ); glVertex3d(-25.0, -25.0, 25.0);
	glTexCoord2f( 0.0f, 0.0f ); glVertex3d(-25.0, 25.0, 25.0);
	glEnd( );


	//top face
	m_textures[BOX_SIDE_TOP].Bind(0);
	glBegin( GL_TRIANGLE_FAN );
	glTexCoord2f( 0.0f, 1.0f ); glVertex3d(25.0, 25.0, -25.0);
	glTexCoord2f( 0.0f, 0.0f ); glVertex3d(25.0, 25.0, 25.0);
	glTexCoord2f( 1.0f, 0.0f ); glVertex3d(-25.0, 25.0, 25.0);
	glTexCoord2f( 1.0f, 1.0f ); glVertex3d(-25.0, 25.0, -25.0);
	glEnd( );

	//left face
	m_textures[BOX_SIDE_90].Bind(0);
	glBegin( GL_TRIANGLE_FAN );
	glTexCoord2f( 0.0f, 0.0f ); glVertex3d(-25.0, 25.0, -25.0);
	glTexCoord2f( 1.0f, 0.0f ); glVertex3d(-25.0, 25.0, 25.0);
	glTexCoord2f( 1.0f, 1.0f ); glVertex3d(-25.0, -25.0, 25.0);
	glTexCoord2f( 0.0f, 1.0f ); glVertex3d(-25.0, -25.0, -25.0);
	glEnd( );

	//right face
	m_textures[BOX_SIDE_270].Bind(0);
	glBegin( GL_TRIANGLE_FAN );
	glTexCoord2f( 1.0f, 1.0f ); glVertex3d(25.0, -25.0, -25.0);
	glTexCoord2f( 0.0f, 1.0f ); glVertex3d(25.0, -25.0, 25.0);
	glTexCoord2f( 0.0f, 0.0f ); glVertex3d(25.0, 25.0, 25.0);
	glTexCoord2f( 1.0f, 0.0f ); glVertex3d(25.0, 25.0, -25.0);
	glEnd( );


	//bottom face
	m_textures[BOX_SIDE_BOTTOM].Bind(0);
	glBegin( GL_TRIANGLE_FAN );			
	glTexCoord2f( 1.0f, 0.0f ); glVertex3d(-25.0, -25.0, -25.0);
	glTexCoord2f( 1.0f, 1.0f ); glVertex3d(-25.0, -25.0, 25.0);
	glTexCoord2f( 0.0f, 1.0f ); glVertex3d(25.0, -25.0, 25.0);
	glTexCoord2f( 0.0f, 0.0f ); glVertex3d(25.0, -25.0, -25.0);
	glEnd( );
	//glEnable(GL_CULL_FACE);
}